# Generated by Django 6.0.5 on 2026-05-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('tamaño', models.CharField(max_length=50)),
                ('peso', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('vacunado', models.BooleanField(default=False)),
                ('adoptado', models.BooleanField(default=False)),
                ('energia', models.IntegerField()),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
    ]
